## Comment out when doing local development
backend:
  name: github
  repo: nsabula/ncd-test
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

# backend:
#   name: git-gateway
# local_backend: true

##
##

media_folder: _assets/uploads/
public_folder: /
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - label: Accountability
    name: accountability
    folder: _accountability/
    create: true
    slug: '{{title}}'
    path: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - {
          label: 'Redirect from',
          name: 'redirect_from',
          widget: 'list',
          required: false,
          default: [],
          field:
            {
              label: 'Redirect Path',
              name: 'redirect_from',
              widget: 'string',
              hint: '/my/other/path',
            },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Adhoc Pages
    name: adhoc-pages
    description: These are pages that are not apart of a data collection that
    folder: pages
    create: true
    slug: '{{title}}'
    path: '{{slug}}'
    editor:
      preview: true
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'single-page',
        }
      - {
          label: 'Published',
          name: 'published',
          description: 'Set to true to publish or false to un-publish a page.',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Permalink',
          name: 'permalink',
          description: 'The URL path for the page.',
          widget: string,
          hint: '/the-page-name/',
        }
      - {
          label: 'Redirect from',
          name: 'redirect_from',
          description: 'An old URL path you want to redirect to this page.',
          widget: 'list',
          required: false,
          default: [],
          field:
            {
              label: 'Redirect Path',
              name: 'redirect_from',
              widget: 'string',
              hint: '/the/old/path/',
            },
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Committees & Communities
    name: committees-communities
    folder: _committees-communities/
    create: true
    slug: '{{name}}'
    path: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', required: false, widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Letters
    name: letters
    folder: _letters/
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - {
          label: 'Policy Areas',
          name: 'policy_areas',
          widget: 'relation',
          collection: 'policy-areas',
          search_fields: ['title'],
          value_field: 'title',
          display_fields: ['title'],
          multiple: true,
          min: 0,
          max: 5,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Council Members
    name: council-members
    folder: _council-members/
    create: true
    slug: '{{member_name}}'
    path: '{{slug}}'
    editor:
      preview: true
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'council-member',
        }
      - { label: 'Member Name', name: 'member_name', widget: 'string' }
      - {
          label: 'Member Title',
          name: 'member_title',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Location',
          name: 'location',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          choose_url: false,
          media_folder: '/_assets/uploads/images',
          public_folder: 'images',
        }
      - {
          label: 'Image Alternative Tag',
          name: 'image_alt_text',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Appearance Order',
          description: 'The order you want the member to appear on the /council-member/ page',
          name: 'order',
          widget: 'number',
        }
      - {
          label: 'Start Date',
          name: 'start_date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Featured Content
    name: featured
    files:
      - label: featured
        name: featured
        file: _data/featured.yaml
        editor:
          preview: true
        fields:
          - label: 'Meetings and Events'
            name: 'meetings'
            widget: 'list'
            fields:
              - label: 'Meetings and Events'
                name: 'featured'
                widget: 'relation'
                collection: 'meetings'
                search_fields: ['title']
                value_field: '{{title}}'
                display_fields: ['title', 'excerpt']
          - label: 'Reports'
            name: 'reports'
            widget: 'list'
            fields:
              - label: 'Featured'
                name: 'featured'
                widget: 'relation'
                collection: 'reports'
                search_fields: ['title']
                value_field: '{{title}}'
                display_fields: ['title']
          - label: 'Newsposts'
            name: 'posts'
            widget: 'list'
            fields:
              - label: 'Featured'
                name: 'featured'
                widget: 'relation'
                collection: 'posts'
                search_fields: ['title']
                value_field: '{{title}}'
                display_fields: ['title']
          - label: 'Letters'
            name: 'letters'
            widget: 'list'
            fields:
              - label: 'Featured'
                name: 'featured'
                widget: 'relation'
                collection: 'letters'
                search_fields: ['title']
                value_field: '{{title}}'
                display_fields: ['title']
          - label: 'Publications'
            name: 'publications'
            widget: 'list'
            fields:
              - label: 'Featured'
                name: 'featured'
                widget: 'relation'
                collection: 'publications'
                search_fields: ['title']
                value_field: '{{title}}'
                display_fields: ['title']
          - label: 'Resources'
            name: 'resources'
            widget: 'list'
            fields:
              - label: 'Featured'
                name: 'featured'
                widget: 'relation'
                collection: 'resources'
                search_fields: ['title']
                value_field: '{{title}}'
                display_fields: ['title']
  - label: Meetings & Events
    name: meetings
    folder: _meetings/
    create: true
    slug: '{{slug}}'
    path: '{{meeting_year}}/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Federal Register Notice',
          name: 'federal_register_notice',
          widget: 'string',
          hint: 'Enter the Federal Register Notice URL.',
          pattern:
            [
              '[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)',
              'Must be a valid URL.',
            ],
        }
      - {
          label: 'Meeting Year',
          name: 'meeting_year',
          widget: 'number',
          default: 2021,
          value_type: 'int',
          min: 1980,
          max: 2030,
          step: 1,
        }
      - {
          label: 'Meeting Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - {
          label: 'Policy Areas',
          name: 'policy_areas',
          widget: 'relation',
          collection: 'policy-areas',
          search_fields: ['title'],
          value_field: 'title',
          display_fields: ['title'],
          multiple: true,
          min: 0,
          max: 5,
          required: false,
        }
      - {
          label: 'Agenda',
          name: 'agenda',
          widget: 'file',
          required: false,
          allow_multiple: false,
          media_folder: '/_assets/uploads/meetings/{{year}}/{{slug}}',
          public_folder: 'meetings/{{year}}/{{slug}}',
        }
      - {
          label: 'Minutes',
          name: 'minutes',
          widget: 'file',
          required: false,
          allow_multiple: false,
          media_folder: '/_assets/uploads/meetings/{{year}}/{{slug}}',
          public_folder: 'meetings/{{year}}/{{slug}}',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Navigation for Site
    name: navigation
    files:
      - label: Navigation
        name: navigation
        file: _data/navigation.yaml
        editor:
          preview: true
        fields:
          - label: 'Primary Navigation Links'
            name: 'primary'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Url'
                name: 'url'
                widget: 'string'
                required: false
              - label: 'Children Dropdown Links'
                name: 'children'
                widget: 'list'
                required: false
                fields:
                  - label: 'Name'
                    name: 'name'
                    widget: 'string'
                  - label: 'Url'
                    name: 'url'
                    widget: 'string'
          - label: 'Secondary Navigation Links'
            name: 'secondary'
            widget: 'list'
            fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Url'
                name: 'url'
                widget: 'string'
  - label: Newsroom
    name: posts
    folder: _posts/
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - { label: 'Excerpt', name: 'excerpt', required: false, widget: 'text' }
      - {
          label: 'Newsroom Type',
          name: 'newsroom_type',
          required: true,
          widget: 'select',
          options:
            [
              '',
              'Funding Opportunities',
              'Speech',
              'Testimonial',
              'Newsletter',
            ],
          default: '',
        }
      - {
          label: 'Policy Areas',
          name: 'policy_areas',
          widget: 'relation',
          collection: 'policy-areas',
          search_fields: ['title'],
          value_field: 'title',
          display_fields: ['title'],
          multiple: true,
          min: 0,
          max: 5,
          required: false,
        }
      - {
          label: 'Document',
          name: 'document',
          widget: 'file',
          required: false,
          allow_multiple: false,
          media_folder: '/_assets/uploads/documents',
          public_folder: 'documents',
        }
      - {
          label: 'Audio',
          name: 'audio',
          widget: 'file',
          required: false,
          allow_multiple: false,
          media_folder: '/_assets/uploads/audios',
          public_folder: 'audios',
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          choose_url: false,
          media_folder: '/_assets/uploads/images',
          public_folder: 'images',
        }
      - {
          label: 'Image Alternative Tag',
          name: 'image_alt',
          widget: 'string',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Policy Areas
    name: policy-areas
    folder: _policy-areas/
    create: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
  - label: Publications
    name: publications
    folder: _publications/
    create: true
    path: '{{publication_year}}/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - {
          label: 'Publication Year',
          name: 'publication_year',
          widget: 'number',
          default: 2021,
          value_type: 'int',
          min: 1980,
          max: 2030,
          step: 1,
        }
      - {
          label: 'Policy Areas',
          name: 'policy_areas',
          widget: 'relation',
          collection: 'policy-areas',
          search_fields: ['title'],
          value_field: 'title',
          display_fields: ['title'],
          multiple: true,
          min: 0,
          max: 5,
          required: false,
        }
      - {
          label: 'Report Document',
          name: 'document',
          widget: 'file',
          required: false,
          allow_multiple: false,
          media_folder: '/_assets/uploads/reports/{{report_year}}',
          public_folder: 'reports/{{report_year}}',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Reports
    name: reports
    folder: _reports/
    create: true
    slug: '{{title}}'
    path: '{{report_year}}/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          date_format: 'MMMM D, YYYY',
          time_format: false,
        }
      - {
          label: 'Report Year',
          name: 'report_year',
          widget: 'number',
          default: 2021,
          value_type: 'int',
          min: 1980,
          max: 2030,
          step: 1,
        }
      - {
          label: 'Policy Areas',
          name: 'policy_areas',
          widget: 'relation',
          collection: 'policy-areas',
          search_fields: ['title'],
          value_field: 'title',
          display_fields: ['title'],
          multiple: true,
          min: 0,
          max: 5,
          required: false,
        }
      - {
          label: 'Report Document',
          name: 'document',
          widget: 'file',
          required: false,
          allow_multiple: false,
          media_folder: '/_assets/uploads/reports/{{report_year}}',
          public_folder: 'reports/{{report_year}}',
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          choose_url: false,
          media_folder: '/_assets/uploads/images',
          public_folder: 'images',
        }
      - {
          label: 'Image Alternative Tag',
          name: 'image_alt',
          widget: 'string',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: Resource Pages
    name: resources
    files:
      - label: Resources
        name: resources
        file: resources/index.md
        editor:
          preview: true
        fields:
          - {
              label: 'Layout',
              name: 'layout',
              widget: 'hidden',
              default: 'single-page',
            }
          - {
              label: 'Permalink',
              name: 'permalink',
              widget: 'hidden',
              default: '/resources/',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: FAQ
        name: faq
        file: resources/faq.md
        editor:
          preview: true
        fields:
          - {
              label: 'Layout',
              name: 'layout',
              widget: 'hidden',
              default: 'single-page',
            }
          - {
              label: 'Permalink',
              name: 'permalink',
              widget: 'hidden',
              default: '/resources/faq/',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
